### ISSUE TITLE
NKThesis TODO List

### ISSUE THREAD

**Issue by Tr0py** [Tr0py/NKU-thesis-template-2020#27]
事情太多，一次性做不完。为了方便repo的维护者沟通，在这记个list。可以讨论沟通。

- [ ] NKT refactor 版本上线：1. overleaf (模板更新) 2. github master 分支更新 3. 新的release
  - [x] review @aqni 的dev-refactor分支代码
  - [x] review dev 分支的效果，与教务处格式要求做对比检查
  - [x] 更新模板说明 (abstract.tex)，解释refactor版本给用户，给 @aqni 加credit
  - [ ] dev分支的实现文档([implementation-of-document-class.md](https://github.com/Tr0py/NKU-thesis-template-2020/blob/dev/docs/implementation-of-document-class.md)) 加入到主页中
  - [ ] 更新overleaf模板版本
  - [x] 与 @aqni 讨论此模板的未来工作 (不足与提升) 
    - [ ] 取消字体文件依赖，使用系统字体，避免侵权 https://github.com/Tr0py/NKU-thesis-template-2020/issues/36
      - [x] 代码开发 https://github.com/Tr0py/NKU-thesis-template-2020/pull/39 
      - [ ] 是否可以用Fandol交论文？
    - [x] 图、表和公式的按章节编号 https://github.com/Tr0py/NKU-thesis-template-2020/discussions/26 https://github.com/Tr0py/NKU-thesis-template-2020/pull/34
- [ ] NKT 宣传
  - [ ] 如何宣传？联系教务处？https://github.com/Tr0py/NKU-thesis-template-2020/discussions/29#discussion-5200033  进度在这里： https://github.com/Tr0py/NKU-thesis-template-2020/issues/32
  - [ ] repo改名？现在的repo带个2020就像是好几年没维护了一样。最好改个名字来显示1）此repo是没有废弃的 2）此repo主要是本科生模板。改名的话会有啥问题吗？https://github.com/Tr0py/NKU-thesis-template-2020/discussions/28#discussion-5200030
    - [x] 改名字可行性
    - [ ] 改成什么

**Comment by aqni** [comment]
### 关于改名

github文档中关于仓库改名的说明
> When you rename a repository, all existing information, with the exception of project site URLs, is automatically redirected to the new name, including: Issues, Wikis, Stars, Followers.
> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.

但是文档中，对[GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites).是否受到影响的说明语焉不详。






详见
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by aqni** [comment]
### 关于宣传

直接联系教务处似乎不可行，当前模板使用者基数不够大，无法引起官方重视。

我认为可行的几个方式：

- 联系在南开大学中有影响力的私人微信公众号，投稿宣传文章
- 在知乎、B站等流量较大社交媒体投稿。
- 在[NKUCS](https://nkucs.icu/#/)之类的信息分享平台投稿。
- 联系物理学院和数学学院（这两个需要latex使用者较多）的模板维护者，将力量集中起来。
- 与硕博latex模板互动，添加友链。

**Comment by aqni** [comment]
等我论文终稿交了（6月5号ddl）没问题的话就合并主分支，然后发布一个release吧。

**Comment by Tr0py** [comment]
听起来不错！
